.spring.application.name=authorization-server

server.port=${PORT}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=create-drop

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.oauth2=TRACE