spring.application.name=msv-habitaciones

# Servidor
server.port=8081

# Base de datos Oracle
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=TU_USUARIO
spring.datasource.password=TU_PASSWORD

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka

eureka.client.service-url.defaultZone=http://localhost:8080/eureka

