spring.application.name=msv-reservas

server.port=8083

# ── Base de datos Oracle ───────────────────────────────
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ── JPA / Hibernate ────────────────────────────────────
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# ── Eureka ─────────────────────────────────────────────
eureka.client.service-url.default=http://localhost:8761/eureka
eureka.instance.instance-id=${spring.apllication.name}:${random.value}
eureka.instance.prefer-ip-address=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000
